### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by suzinyou** [jsconfkorea/2020.jsconfkorea.com#21]
Internet explorer에서 일부 애니메이션 및 기능이 정상적으로 실행되지 않는 버그

**테스트 환경**
 - windows 10
- Internet explorer 11  (microsoft edge에선 다 잘 되어서 굳이 지원해야하나 싶지만 우선 보고합니다..)
- display resolution (3200 x 1800)

----

![Annotation 2020-06-10 144226](https://user-images.githubusercontent.com/7042047/84231582-700b0280-ab29-11ea-946a-fb9ccc28eefc.png)

애니메이션
- 햄버거 호버시 X로 변하지 않음
- 홈페이지 제목 애니메이션 작동 x
- 홈페이지 "집" 도형 애니메이션 작동 x
- Back to top  버튼 렌더링 오류
![Annotation 2020-06-10 144136](https://user-images.githubusercontent.com/7042047/84231576-6ed9d580-ab29-11ea-8769-4d743d7a0cb9.png)

레이아웃
- 홈 화면 제목이 잘려 나옴
- 홈 화면 일부 스크롤 가능해서 하단 메뉴 밑으로 공백 생기는 현상

기능 오류
- 뉴스레터 버튼 누를시 팝업 등장하지 않음
- 햄버거 버튼 동작하지 않음

**Comment by mojosoeun** [comment]
ie edge에서는 잘 나올까요?

**Comment by ysm-dev** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/18487241/89994984-d0eabe80-dcc3-11ea-8ecf-1ae1f7376553.png">

IE 접속률이 0%라 IE 지원은 드랍합니다.
