### ISSUE TITLE
한국어 발표 미리보기 잘리는 현상

### ISSUE THREAD

**Issue by suzinyou** [jsconfkorea/2020.jsconfkorea.com#35]
### Subject of the issue
아이폰7 크롬 한국어 발표 미리보기에서 다음줄이 살짝 보임.
![KakaoTalk_20200813_164050356](https://user-images.githubusercontent.com/7042047/90107576-fc34e280-dd83-11ea-9dd6-c3ed8afcc812.jpg)

### Your environment
iPhone 7
chrome iOS app

### Steps to reproduce
iPhone7에서 chrome 앱을 켜고 https://jsconfkorea.com/ko/speakers 로 간다.. (데스트탑 chrome inspect tool에서 iphone7 dimension 선택하면 재현 안됨ㅠ)

### Expected behaviour
3줄만 보이고 짤려야함

### Actual behaviour
4번째 줄이 살짝 보임

**Comment by ysm-dev** [comment]
@suzinyou 해결했습니다! 확인하시고 이슈 Close해주세요!!
