### ISSUE TITLE
발표요약 markdown link표기 오류

### ISSUE THREAD

**Issue by suzinyou** [jsconfkorea/2020.jsconfkorea.com#39]
### Subject of the issue

- 발표 요약에 링크가 있는 경우 미리보기에서 마크다운이 그대로 \[...\]\(....\) 형태로 보이고, 
- 상세보기에서는 hyperlink임이 딱히 표지되지 않는 문제 (이건 우선순위 떨어지는 것 같지만 밑줄 추가 가능한가요?)
- 영어 한국어 동일

### Your environment
Chrome

### Steps to reproduce
https://jsconfkorea.com/ko/speakers
https://jsconfkorea.com/en/speakers

Ben님 카드 확인

### Expected behaviour

- 미리보기에서는 적어도 \[....\]에 들어가는 링크 텍스트만 보이고 (또는 밑줄 포함)
- 상세보기에서는 링크가 걸린 텍스트에 밑줄이 보인다.

### Actual behaviour
- 미리보기에서 마크다운 그대로 보임
![image](https://user-images.githubusercontent.com/7042047/90330372-4e297280-dfe7-11ea-8b41-945ee7e7fd1d.png)

- 상세보기에서 링크 밑줄 없음
![image](https://user-images.githubusercontent.com/7042047/90330457-c5f79d00-dfe7-11ea-91d5-4d20719cdae1.png)

**Comment by ysm-dev** [comment]
@suzinyou 감사합니다! 수정했습니다. 확인하고 이슈 Close 해주세요.
